### ISSUE TITLE
请问ChromeDriver的版本是多少啊

### ISSUE THREAD

**Issue by sunshuyang** [rmb122/Delete-my-hisroy-in-tieba#1]
请问ChromeDriver的版本是多少啊，使用ChromeDriver2.9直接停止工作了

**Comment by rmb122** [comment]
最新版就行了0.0 有没有啥错误信息

**Comment by rmb122** [comment]
应该是时间设的短了, 我调成了两秒, 更新一下运行再看看会不会炸掉 0.0

**Comment by sunshuyang** [comment]
昨晚解决了

64.0.3282.168 (正式版本) （64 位） 对应 2.35版本，使用错误版本可能直接停止工作

可以在chromedriver/2.35/notes.txt 文件中查看

----------ChromeDriver v2.35 (2018-01-10)----------
Supports Chrome v62-64
Resolved issue 2191: Executing JavaScript code fails if the script returns no result [[Pri-1]]
Resolved issue 2183: Connections Aren't Persistent [[Pri-2]]
Resolved issue 2207: Some mobile emulation devices do not work [[Pri-2]]
Resolved issue 2177: Get local storage returns command names in Chrome 63 [[Pri-2]]
Resolved issue 2179: absolute time on log entries [[Pri-2]]

**Comment by rmb122** [comment]
噗, 那就ok~
