### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by jmgllt59** [rmb122/Delete-my-hisroy-in-tieba#11]
![屏幕截图(252)](https://user-images.githubusercontent.com/66712823/84227375-d9354a80-ab16-11ea-9c55-761371ce0f94.png)
：3我也是闪退，不知道什么问题，看教程来的，程序立刻就运行不了

**Comment by rmb122** [comment]
看上去只是 get 了个地址就炸了, 没有复现成功, 可以尝试一下重装环境看看还有没有错误
