### ISSUE TITLE
似乎无法删除回复了

### ISSUE THREAD

**Issue by Lily138** [rmb122/Delete-my-hisroy-in-tieba#12]
额(⊙o⊙)…百度的回复页面改版以后似乎没有办法删除回复了

**Comment by rmb122** [comment]
能提供报错信息么, 我刚刚测试了下是没问题的

**Comment by xx13295** [comment]
删除回复可能每天有限制   吧  我用百度贴吧软件去删除回复 到一个数的时候会提示不允许删除，不知道这个 项目代码会被限制嘛

**Comment by rmb122** [comment]
> 删除回复可能每天有限制 吧 我用百度贴吧软件去删除回复 到一个数的时候会提示不允许删除，不知道这个 项目代码会被限制嘛

每天 30 贴，此项目会被限制，所以推荐放到服务器上自动跑
