### ISSUE TITLE
两个关于网络环境的建议

### ISSUE THREAD

**Issue by mokeyjay** [rmb122/Delete-my-hisroy-in-tieba#15]
鉴于国内的网络环境，建议在 `pip install xxx` 前添加一行
`pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple`
将 pip 设为清华源，避免因网络问题报错

其次是在 `sess = requests.session()` 后添加一行
`sess.trust_env = False`
以忽略系统的代理配置，避免在配置了科学上网的系统中可能的报错 **Not supported proxy scheme None**

Python 版本 3.9.1。感谢你的项目

**Comment by rmb122** [comment]
感觉建议~ https://github.com/rmb122/Delete-my-hisroy-in-tieba/commit/e4e209b3e73c45a9e1db10d8468856ca9f5608d4
