### ISSUE TITLE
试图使用async请求

### ISSUE THREAD

**Issue by tleydxdy** [rmb122/Delete-my-hisroy-in-tieba#16]
我观察到虽然说每天删除的上限是30条回复，但是基本上一天都能删除几百条，而且每天删掉的数量还不一样。所以感觉这个上限是每多少时间才在后台检查一次的。那么可以试试用async的方法一次发送很多个请求（而不是等请求返回了才发送下一个）来提升每天可以删除的帖子的数量。

**Comment by rmb122** [comment]
度娘这么累就不迫害她了 233
