### ISSUE TITLE
Delete-reply.py中的SyntaxError

### ISSUE THREAD

**Issue by Tsuk1ko** [rmb122/Delete-my-hisroy-in-tieba#2]
https://github.com/rmb122/Delete-my-hisroy-in-tieba/blob/2bb0e05a00578e49cd90a4e7e65df422c625a694/Delete-reply.py#L84
```
SyntaxError: Non-ASCII character '\xe8' in file /home/Delete-my-hisroy-in-tieba/Delete-reply.py on line 84, but no encoding declared
```
删除注释后正常，或者貌似是要加上`# -*- coding:utf-8 -*-`之类的？
\_(:3」∠)_

**Comment by rmb122** [comment]
python3 [默认](https://www.python.org/dev/peps/pep-3120/)应该是用 utf-8 解码的 0.0，可能是出现一些奇怪的 bug。不过加上 `# -*- coding: utf-8 -*-` 也不费事 233

**Comment by Tsuk1ko** [comment]
我是直接用 linux 系统自带的 python2 运行的，看来2默认不 utf-8，也不是什么大问题2333

**Comment by rmb122** [comment]
如果用 python2 的话 print() 不会出问题么，应该会跳一堆 Exception 吧 0.0

**Comment by Tsuk1ko** [comment]
python 2.7.9 运行`Delete-reply.py`没有问题，`TieBaDeleter.py`暂时没有需求所以没有去用，不知是否会有问题

**Comment by rmb122** [comment]
最好还是用 python3 吧 \_(:3」∠)\_ 不然可能会产生一些奇妙的问题 233

**Comment by Tsuk1ko** [comment]
好的23333 \_(:3」∠)_
