### ISSUE TITLE
运行了程序 但帖子没有删除？

### ISSUE THREAD

**Issue by ItsMMJ** [rmb122/Delete-my-hisroy-in-tieba#20]
![Snipaste_2021-10-05_00-10-12](https://user-images.githubusercontent.com/71795959/135886290-833a9c61-eac8-47fc-8977-c99bf0df3a70.jpg)
程序运行到如图所示的阶段 就会自动关闭 然后我去查看发帖纪录 没有被删除 是哪里没有设置对吗？谢谢

**Comment by rmb122** [comment]
在脚本运行的目录按住 shift 同时按下鼠标右键，会有在当前目录打开 powershell / cmd 的选项，在这个里面运行 python DeleteMyHistory.py ，如果出现错误应该会有报错输出，麻烦贴一下我看看 👀

**Comment by ItsMMJ** [comment]
好的 我刚才试了一下 是这样的 不过今天我已经手动删除帖子到上限了 不知道有没有影响
![Snipaste_2021-10-05_17-20-07](https://user-images.githubusercontent.com/71795959/135996429-d2ae9d8c-5d74-40b4-95e9-3691ad3203cd.jpg)

**Comment by rmb122** [comment]
我这里测了下是没有报错的, 在百度上搜了下类似的错误貌似是 requests 版本比较低或者代理的问题, 尝试重新装一下或者关一下代理?

**Comment by ItsMMJ** [comment]
好的 谢谢 明天删帖限制刷新了 我再关闭代理试试看

**Comment by ItsMMJ** [comment]
刚才关闭代理 成功删帖了 问题已解决
另外 虽然显示每天限制删除30条 但我这实际都能删15页 240条
