### ISSUE TITLE
beautiful soup feature设定报错

### ISSUE THREAD

**Issue by LHansoon** [rmb122/Delete-my-hisroy-in-tieba#23]
- macOS
- py38
- config thread disabled因为发帖少手动删了（
`html = bs4.BeautifulSoup(res.text, "lxml")`这一行有问题，没用过beautifulsoup，但是看了一下res.text发现是html，遂碰运气把lxml换成了html.parser就成了
希望有帮助
顺便感叹一下我居然有那么多回复。。。

**Comment by rmb122** [comment]
lxml 是个独立的 package, 在 https://github.com/rmb122/Delete-my-hisroy-in-tieba/blob/master/requirements.txt 里面有标 233
