### ISSUE TITLE
Limit exceeded, exiting.

### ISSUE THREAD

**Issue by s44759** [rmb122/Delete-my-hisroy-in-tieba#25]
这个是触发了哪方面的限制🤣试了下手动还可以删回复，好像不是百度贴吧每日的删回复上限
Limit exceeded, exiting.
0 replies has been deleted, left 100 replies due to limit exceeded

**Comment by rmb122** [comment]
有时候部分帖子因为贴吧的 Bug 是删不掉的, 可以调整页数跳过试试

**Comment by Johkiin** [comment]
这个可以用于吧务删帖吗？比如匹配到某些关键词就自动删帖那种
