### ISSUE TITLE
大佬 你写的贴吧删帖软件打开闪退要咋整

### ISSUE THREAD

**Issue by Neo010Lee** [rmb122/Delete-my-hisroy-in-tieba#33]
powershell 打开 也是闪退 ，什么信息也没提示。

**Comment by rmb122** [comment]
能提供在 powershell 下运行的截图么?

**Comment by Neo010Lee** [comment]
![image](https://github.com/rmb122/delete-my-history-in-tieba/assets/125844106/803d5f51-30b3-4f4c-abe6-c99dc91b9155)

**Comment by Neo010Lee** [comment]
大佬你看下

**Comment by rmb122** [comment]
有一说一确实没遇到过这种问题 = =, 你有改过配置文件么? 实在不行的话可以试试自己下个 python 运行下脚本看看啥情况.

**Comment by Neo010Lee** [comment]
大佬啊，我是小白不懂啊。

**Comment by rmb122** [comment]
https://github.com/rmb122/delete-my-history-in-tieba/blob/14cb102acf8fe05dde0e07104e586037a8966bb2/Guide.md
可以参考这个

**Comment by Neo010Lee** [comment]
![image](https://github.com/rmb122/delete-my-history-in-tieba/assets/125844106/92c46b32-ce2b-457c-81c7-c97300eaff2d)
大佬这个是在哪里下载

**Comment by Neo010Lee** [comment]
![image](https://github.com/rmb122/delete-my-history-in-tieba/assets/125844106/e679283d-765d-42bc-9ae1-f8c4caf6d405)
zehs这个又在哪里啊，大佬

**Comment by rmb122** [comment]
https://github.com/rmb122/delete-my-history-in-tieba/archive/refs/tags/v1.1.1.zip 下载完后按照之前的步骤, 就最后一步用 python 运行 DeleteMyHistory.py 就行

**Comment by Neo010Lee** [comment]
大佬可以了，爱你哟，那个现在我的贴吧是能删除几百个帖子，但是我回复好像没删除啊，而且我删除的帖子在回收站里，没删掉，这个要咋整。

**Comment by n0099** [comment]
https://tieba.baidu.com/pmc/recycle?tab=self 中的记录等半年就会消失

**Comment by Neo010Lee** [comment]
好的，大佬爱你哟。
