### ISSUE TITLE
大佬想问下自动闪退该怎么处理

### ISSUE THREAD

**Issue by jintianyaoshou** [rmb122/Delete-my-hisroy-in-tieba#34]
双击后一直就是闪退状态
![image](https://github.com/rmb122/delete-my-history-in-tieba/assets/152580236/52f10875-a60c-4fd1-858e-63fe714a0601)

**Comment by rmb122** [comment]
这个是cookie没复制对, 确认下是否按照教程里来的? 需要登录后在 https://tieba.baidu.com/ 下复制
