### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb6 in position 873: illegal multibyte sequence

### ISSUE THREAD

**Issue by rosaetempus** [rmb122/Delete-my-hisroy-in-tieba#37]
Traceback (most recent call last):
  File "DeleteMyHistory.py", line 321, in <module>
  File "DeleteMyHistory.py", line 298, in main
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb6 in position 873: illegal multibyte sequence

解决方式：
找到cookie中的乱码，连同最后的‘;’一起删除即可。
![QQ截图20240316151933](https://github.com/rmb122/delete-my-history-in-tieba/assets/25456865/93c99216-f5ed-41fc-9609-abf3bb946ff0)

**Comment by rmb122** [comment]
https://github.com/rmb122/delete-my-history-in-tieba/commit/82ebd5775d4437c2e5a4a3524b35e0ee1037b871

在FAQ里面提及了一下
