### ISSUE TITLE
可能是编码有误的报错，希望收到回复

### ISSUE THREAD

**Issue by lumen1023** [rmb122/Delete-my-hisroy-in-tieba#39]
Traceback (most recent call last):
  File "DeleteMyHistory.py", line 321, in <module>
  File "DeleteMyHistory.py", line 298, in main
UnicodeDecodeError: 'gbk' codec can't decode byte 0xfe in position 4: illegal multibyte sequence
[110788] Failed to execute script DeleteMyHistory

尝试查询一些资料和咨询GPT更改源码 依旧无法解决 希望收到您的回复

**Comment by n0099** [comment]
#36 #37

**Comment by lumen1023** [comment]
> #36 #37

谢谢已经解决，也确实是编码的问题 我换了一台服务器系统默认是ansi编码的就可以了，感谢提醒

**Comment by rmb122** [comment]
在代码里把问题解决了一下, https://github.com/rmb122/delete-my-history-in-tieba/commit/f1db42bca5b33cc89c9131c564dd0bb27d97aec5 可以再试试看
