### ISSUE TITLE
pip install -r requirements.txt 失败

### ISSUE THREAD

**Issue by tangzhi1996** [rmb122/Delete-my-hisroy-in-tieba#40]
异常提示 rock@hinlink-ht2:~/桌面/delete-my-history-in-tieba$ pipx install -r requirements.txt
usage: pipx [-h] [--version]
            {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,environment,completions}
            ...
pipx: error: unrecognized arguments: -r

**Comment by rmb122** [comment]
你应该用 pip 而不是 pipx, 这两个不完全兼容
