### ISSUE TITLE
删除不了帖子了

### ISSUE THREAD

**Issue by bntP5Zyf** [rmb122/Delete-my-hisroy-in-tieba#6]
删完发现帖子没有被删,手动删除提示系统繁忙。

**Comment by rmb122** [comment]
一天删除有上限的0.0 如果是已经删了一些再报错的话应该是到上限了, 可以分几天慢慢来

**Comment by bntP5Zyf** [comment]
是一个帖子也删不了。没有到达上限。

**Comment by rmb122** [comment]
好的 有空我去看看0.0 可能被识别了

**Comment by rmb122** [comment]
刚刚测试了下, 发了几贴没啥问题, 可以删掉 0.0 我再继续测试几天吧. 可能还是连续删除被识别的问题

**Comment by bntP5Zyf** [comment]
好像又可以了，谢谢了。

**Comment by rmb122** [comment]
嗯嗯
