### ISSUE TITLE
看起来不会删除回复

### ISSUE THREAD

**Issue by PalAlexx** [rmb122/Delete-my-hisroy-in-tieba#9]
主题和关注很正常可以删掉与取关。但是回复这里 运行时看上去没问题 就是删不掉

**Comment by rmb122** [comment]
我这边测试了一下能正常工作 0.0 可能是上限达到了, 但没有正常返回错误信息, 过一天再删除试试

**Comment by PalAlexx** [comment]
是的 ，今天删除正常啦 感谢 很好用
